language: generic
sudo: true
dist: trusty

before_install:
    - sudo apt-get update
    - sudo apt-get install qemu-system-arm wget sshpass
    
install:
    
before_script:

script:
    - sudo ln -s /usr/bin/arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gcc; sudo ln -s /usr/bin/arm-linux-gnueabihf-ld /usr/bin/arm-linux-ld; sudo ln -s /usr/bin/arm-linux-gnueabihf-objdump /usr/bin/arm-linux-objdump ; sudo ln -s /usr/bin/arm-linux-gnueabihf-objcopy /usr/bin/arm-linux-objcopy ; sudo ln -s /usr/bin/arm-linux-gnueabihf-ar /usr/bin/arm-linux-ar ;  cd monome-snd ; make ;