language: generic
sudo: true
dist: trusty

before_install:
    - sudo apt-get update
    - sudo apt-get install qemu-system-arm wget sshpass
    
install:
    - ls
    
before_script:
    - ls
    
script:
    - pwd